<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Comments</name>
   <tag></tag>
   <elementGuidId>82865d0d-ff0f-4257-a786-57097c185c73</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-TextArea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-container&quot;)/div[@class=&quot;container&quot;]/div[1]/div[1]/section[@class=&quot;main&quot;]/div[@class=&quot;col1&quot;]/div[@class=&quot;widget&quot;]/div[@class=&quot;class_box_shadow dashboardcreernote&quot;]/div[@class=&quot;content-widget-form&quot;]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[@class=&quot;overlay-row&quot;]/div[1]/div[@class=&quot;overlay-row&quot;]/div[@class=&quot;ovrl-col2&quot;]/textarea[@class=&quot;gwt-TextArea&quot;]</value>
   </webElementProperties>
</WebElementEntity>
