<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ExpiryDate</name>
   <tag></tag>
   <elementGuidId>9b4e5f10-d191-43ef-834d-79a5b0f17acb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;PP&quot;]/table[4]/tbody/tr/td/table/tbody/tr[2]/td[3]/font</value>
   </webElementProperties>
</WebElementEntity>
