<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DeletePassport</name>
   <tag></tag>
   <elementGuidId>7b3eb9b1-7e2f-4894-b030-950e4495ce62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;PP&quot;]/table[4]/tbody/tr/td/table/tbody/tr[2]/td[1]/a[2]/img</value>
   </webElementProperties>
</WebElementEntity>
