<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CountryVerify</name>
   <tag></tag>
   <elementGuidId>80b1a892-9576-49d1-bbbd-e80e3abd1351</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;TD&quot;]/table[4]/tbody/tr/td/table/tbody/tr[2]/td[3]/font</value>
   </webElementProperties>
</WebElementEntity>
