<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NumberVerify</name>
   <tag></tag>
   <elementGuidId>63a78011-e54e-4949-89f0-3a493e6070fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;TD&quot;]/table[4]/tbody/tr/td/table/tbody/tr[2]/td[1]</value>
   </webElementProperties>
</WebElementEntity>
