<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PassportNumberVerify</name>
   <tag></tag>
   <elementGuidId>78a43b6b-3773-480d-b260-ac6fe01072be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;PP&quot;]/table[4]/tbody/tr/td/table/tbody/tr[2]/td[1]</value>
   </webElementProperties>
</WebElementEntity>
