<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IDNumberVerify</name>
   <tag></tag>
   <elementGuidId>e9e3bebd-7f91-46f6-8aab-231a8973e95a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ID&quot;]/table[4]/tbody/tr/td/table/tbody/tr[2]/td[1]</value>
   </webElementProperties>
</WebElementEntity>
