<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DrivingLicencePlaceOfIssueVerify</name>
   <tag></tag>
   <elementGuidId>3c1bc0f8-9715-4acb-98f9-d2dfc7c6daa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;DL&quot;]/table[4]/tbody/tr/td/table/tbody/tr[2]/td[3]/font</value>
   </webElementProperties>
</WebElementEntity>
