<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IDCountryVerify</name>
   <tag></tag>
   <elementGuidId>17f64379-1f3a-4c43-b23f-5c44c8f336f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ID&quot;]/table[4]/tbody/tr/td/table/tbody/tr[2]/td[2]/font</value>
   </webElementProperties>
</WebElementEntity>
