<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DrivingLicenceDateOfIssueVerify</name>
   <tag></tag>
   <elementGuidId>1a506a5f-1436-4a1f-a5a3-6f0c83e09fae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;DL&quot;]/table[4]/tbody/tr/td/table/tbody/tr[2]/td[4]/font</value>
   </webElementProperties>
</WebElementEntity>
